# Generated by Django 5.0.7 on 2024-07-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('asset_id', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Extensions', 'Extensions'), ('Banners', 'Banners'), ('Screens', 'Screens')], max_length=20)),
                ('comments', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.asset')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(blank=True, max_length=255, null=True)),
                ('new_location', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.asset')),
            ],
        ),
    ]
